[package]
name = "reduction-of-sentence-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
chrono = "0.4.19"
chronoutil = "0.2.3"
gloo-console = "0.2.1"
web-sys = "0.3.56"
