[package]
name = "calc-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
chrono = { version = "0.4.19", features = ["serde"] }
chronoutil = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"